### ISSUE TITLE
Regarding Facebook video downloader script 

### ISSUE THREAD

**Issue by Archanaa08** [NicheOffice/facebook-video-downloader#1]
Hi ,iam unable to find "You can change or remove this text. And you can add ad to below.thia part in this php script,How can i edit this line in php,where do i find this line...

**Comment by ahmethakanbesel** [comment]
You can find it here:
https://github.com/NicheOffice/facebook-video-downloader/blob/master/language/en.php

**Comment by Archanaa08** [comment]
Thanks for your valuable response to my request sir....

1.Another request sir how can I add custom pages like about us, contact
form....

2.Can i edit my own text in home page???
